name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "feature/**" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual trigger

env:
  IMAGE_NAME: cicd-shop
  CONTAINER_REGISTRY: docker.io  # or ghcr.io for GitHub Container Registry
  K8S_NAMESPACE: cicd-shop
  ARM_CLIENT_ID: ${{ secrets.APP_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.APP_PASS }}
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Set up Maven Wrapper permissions
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml -DskipTests

    - name: Run Unit Tests
      run: ./mvnw test -DexcludeTags=integration
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Upload coverage to Coveralls
      if: github.ref == 'refs/heads/main'
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: ./target/site/jacoco/jacoco.xml
        flag-name: run-${{ github.run_id }}
        parallel: true
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan
      continue-on-error: true

    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false

    - name: Get VM Public IP
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: ip
      run: |
        IP=$(terraform output -raw public_ip_address)
        echo "vm_public_ip=$IP" >> $GITHUB_OUTPUT

    - name: Show VM Connection Info
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "VM Public IP: ${{ steps.ip.outputs.vm_public_ip }}"
        echo "Connect using: ssh ${{ vars.ADMIN_USERNAME || 'azureuser' }}@${{ steps.ip.outputs.vm_public_ip }}"