name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "development", "feature/**" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual trigger

env:
  IMAGE_NAME: cicd-shop
  CONTAINER_REGISTRY: docker.io  # or ghcr.io for GitHub Container Registry
  K8S_NAMESPACE: cicd-shop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Set up Maven Wrapper permissions
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml -DskipTests

    - name: Run Unit Tests
      run: ./mvnw test

    - name: Run Integration Tests
      run: ./mvnw verify -Pintegration-test
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Upload coverage to Coveralls
      if: github.ref == 'refs/heads/main'
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: ./target/site/jacoco/jacoco.xml
        flag-name: run-${{ github.run_id }}
        parallel: true
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check